import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        outline: "#777587",
        surface: "#fcf8ff",
        background: "#fcf8ff",
        "tertiary-fixed": "#ffdbcc",
        "secondary-fixed-dim": "#b7c8e1",
        "on-tertiary-fixed-variant": "#7b2f00",
        "primary-fixed-dim": "#c3c0ff",
        secondary: "#505f76",
        "on-tertiary-container": "#ffd2be",
        "on-primary-container": "#dad7ff",
        "tertiary-fixed-dim": "#ffb695",
        primary: "#3525cd",
        "surface-dim": "#dcd8e5",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#0f0069",
        "on-surface-variant": "#464555",
        "primary-fixed": "#e2dfff",
        "on-secondary-fixed-variant": "#38485d",
        "error-container": "#ffdad6",
        "inverse-surface": "#302f39",
        "on-background": "#1b1b24",
        "on-error": "#ffffff",
        "secondary-container": "#d0e1fb",
        "inverse-primary": "#c3c0ff",
        "on-tertiary": "#ffffff",
        "primary-container": "#4f46e5",
        "secondary-fixed": "#d3e4fe",
        "surface-container-low": "#f5f2ff",
        "surface-container": "#f0ecf9",
        "surface-tint": "#4d44e3",
        "surface-bright": "#fcf8ff",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#54647a",
        "on-primary-fixed-variant": "#3323cc",
        "surface-variant": "#e4e1ee",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#c7c4d8",
        "surface-container-high": "#eae6f4",
        "on-primary": "#ffffff",
        "on-surface": "#1b1b24",
        "inverse-on-surface": "#f3effc",
        "tertiary-container": "#a44100",
        "on-secondary-fixed": "#0b1c30",
        "on-tertiary-fixed": "#351000",
        error: "#ba1a1a",
        tertiary: "#7e3000",
        "surface-container-highest": "#e4e1ee",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-xs": "0.25rem",
        "stack-sm": "0.5rem",
        gutter: "1.5rem",
        "container-max": "1440px",
        "margin-page": "2rem",
        "stack-lg": "1.5rem",
        "stack-md": "1rem",
      },
      fontFamily: {
        "label-md": ["Inter", "sans-serif"],
        h2: ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        h1: ["Inter", "sans-serif"],
        micro: ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        h2: [
          "18px",
          { lineHeight: "26px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "label-sm": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "500" },
        ],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "display-sm": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        h1: [
          "20px",
          { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        micro: [
          "11px",
          { lineHeight: "14px", letterSpacing: "0.03em", fontWeight: "600" },
        ],
        "display-lg": [
          "30px",
          { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
      },
    },
  },
  plugins: [],
};
export default config;
